name: mgh
description: "A professional management and booking app for Muktinath Guesthouse."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.0
  url_launcher: ^6.3.2
  workmanager: ^0.9.0+3
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Ensure these folders exist in your project root
  assets:
    - assets/images/
    - assets/icons/
